# Generated by Django 3.2.16 on 2022-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoTracker",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("latest", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField(max_length=200)),
            ],
        ),
    ]
